Handle redirected output better (#3)
I ran into two problems when `stdout` was redirected, like in a shell script. This change fixes both.

1. When the user was prompted for a two-factor auth code, the prompt would be hidden by the redirect, which made the program look like it was hung.
    a. Fix: Whenever we prompt the user for input, first check `sys.stdout.isatty()` to see if stdout is a TTY or if output is being redirected. If stdout is redirected then just fail, ideally with instructions on how the user can fix the problem and try again.
2. When running `aws-jumpcloud exec ...`, the output of `aws-jumpcloud` itself was mixed in with the output of the program you were running, so you couldn't safely capture that in a variable.
    a. Fix: Send error and debug to `stderr`. This doesn't affect output from normal operations like `aws-jumpcloud list`, `aws-jumpcloud add`, etc.

Example of how this works in practice:

```
$ BUCKETS="$(aws-jumpcloud exec duff -- aws s3 ls)"
Using JumpCloud login details from your OS keychain.

Error: Multi-factor authentication is required on your JumpCloud account.
Run "aws-jumpcloud rotate duff" interactively to refresh
the temporary credentials in your OS keychain, then try again.
```
```
$ aws-jumpcloud rotate duff
Using JumpCloud login details from your OS keychain.
Enter your JumpCloud multi-factor auth code: 123456
Attempting SSO authentication to Amazon Web Services...

AWS temporary session rotated; new session valid until Tue Nov 20 23:42:45 2018 UTC.
```
```
$ BUCKETS="$(aws-jumpcloud exec duff -- aws s3 ls)"
$ echo "$BUCKETS"
2018-11-14 17:09:32 duff-logs-us-east-1
2018-11-13 10:40:21 duff-data-backup
```

This also bumps the version number to 1.0.2.